name: SkWaze
author: Weefle
version: 2.2.2
description: The coolest Skript's addon
depends: [Skript]
softdepends: [BossBarAPI, Citizens, Builder, ProtocolLib, LibsDisguises, HolographicDisplays, Netherboard, BungeeBridgeC]
main: fr.weefle.waze.Waze